- name: Ping Pong Playbook
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Download earthrise.jpg to specified path
      ansible.windows.win_get_url:
        url: http://www.example.com/earthrise.jpg
        dest: C:\Users\RandomUser\earthrise.jpg
    
    - name: Download earthrise.jpg to specified path only if modified
      ansible.windows.win_get_url:
        url: http://www.example.com/earthrise.jpg
        dest: C:\Users\RandomUser\earthrise.jpg
        force: false
    
    - name: Download earthrise.jpg to specified path through a proxy server.
      ansible.windows.win_get_url:
        url: http://www.example.com/earthrise.jpg
        dest: C:\Users\RandomUser\earthrise.jpg
        proxy_url: http://10.0.0.1:8080
        proxy_username: username
        proxy_password: password
    
    - name: Download file from FTP with authentication
      ansible.windows.win_get_url:
        url: ftp://server/file.txt
        dest: '%TEMP%\ftp-file.txt'
        url_username: ftp-user
        url_password: ftp-password
    
    - name: Download src with sha256 checksum url
      ansible.windows.win_get_url:
        url: http://www.example.com/earthrise.jpg
        dest: C:\temp\earthrise.jpg
        checksum_url: http://www.example.com/sha256sum.txt
        checksum_algorithm: sha256
        force: True
    
    - name: Download src with sha256 checksum url
      ansible.windows.win_get_url:
        url: http://www.example.com/earthrise.jpg
        dest: C:\temp\earthrise.jpg
        checksum: a97e6837f60cec6da4491bab387296bbcd72bdba
        checksum_algorithm: sha1
        force: True