- name: Ping Pong Playbook
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Replace the entries of Deny log on locally
      ansible.windows.win_user_right:
        name: SeDenyInteractiveLogonRight
        users:
        - Guest
        - Users
        action: set
    
    - name: Add account to Log on as a service
      ansible.windows.win_user_right:
        name: SeServiceLogonRight
        users:
        - .\Administrator
        - '{{ansible_hostname}}\local-user'
        action: add
    
    - name: Remove accounts who can create Symbolic links
      ansible.windows.win_user_right:
        name: SeCreateSymbolicLinkPrivilege
        users:
        - SYSTEM
        - Administrators
        - DOMAIN\User
        - group@DOMAIN.COM
        action: remove
    
    - name: Remove all accounts who cannot log on remote interactively
      ansible.windows.win_user_right:
        name: SeDenyRemoteInteractiveLogonRight
        users: []